/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author Asadujjaman(181311066)
 */
public class bmi extends javax.swing.JFrame {

    /**
     * Creates new form bmi
     */
    public bmi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mbt = new javax.swing.JComboBox<>();
        fbt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        abt = new javax.swing.JTextField();
        bbt = new javax.swing.JTextField();
        abbt = new javax.swing.JTextField();
        obt = new javax.swing.JTextField();
        rhp = new javax.swing.JTextField();
        rhn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btestimate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel14.setText("%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mother blood type");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Father blood type ");

        mbt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "A Rh +", "A Rh -", "B Rh +", "B Rh -", "AB Rh +", "AB Rh -", "O Rh +", "O Rh -" }));

        fbt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "A Rh +", "A Rh -", "B Rh +", "B Rh -", "AB Rh +", "AB Rh -", "O Rh +", "O Rh -" }));
        fbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chance for type A");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chance for type B");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chance for type AB");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chance for type O");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chance for Rh+ ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Chance for Rh- ");

        obt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtActionPerformed(evt);
            }
        });

        rhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhpActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("%");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("%");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("%");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("%");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("%");

        btestimate.setText("estimate");
        btestimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btestimateActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/icons8-replay-20.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("<html> <h1><u>Blood Group Estimator</h1>");

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Exit");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(7, 7, 7)))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(abbt)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(bbt))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(abt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rhn)
                                        .addComponent(rhp)
                                        .addComponent(obt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(btestimate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fbt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mbt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fbt, mbt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btestimate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(abt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(abbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(rhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtActionPerformed

    private void rhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rhpActionPerformed

    private void fbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fbtActionPerformed

    private void btestimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btestimateActionPerformed
        // TODO add your handling code here:
        if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("93.75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("93.75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("A Rh +") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("93.75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("93.75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("A Rh -") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("0");
            bbt.setText("93.75");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("0");
            bbt.setText("93.75");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("B Rh +") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("18.75");
            bbt.setText("18.75");
            abbt.setText("56.25");
            obt.setText("6.25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("0");
            bbt.setText("93.75");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("0");
            bbt.setText("93.75");
            abbt.setText("0");
            obt.setText("6.25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("B Rh -") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("25");
            bbt.setText("25");
            abbt.setText("50");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("25");
            bbt.setText("25");
            abbt.setText("50");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("AB Rh +") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("50");
            bbt.setText("12.5");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("12.5");
            bbt.setText("50");
            abbt.setText("37.5");
            obt.setText("0");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("25");
            bbt.setText("25");
            abbt.setText("50");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("25");
            bbt.setText("25");
            abbt.setText("50");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("AB Rh -") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("0");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("100");
            rhp.setText("93.75");
            rhn.setText("6.25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("0");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("100");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("A Rh +")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("A Rh -")) {
            abt.setText("75");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("B Rh +")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("B Rh -")) {
            abt.setText("0");
            bbt.setText("75");
            abbt.setText("0");
            obt.setText("25");
            rhp.setText("0");
            rhn.setText("100");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("AB Rh +")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("AB Rh -")) {
            abt.setText("50");
            bbt.setText("50");
            abbt.setText("0");
            obt.setText("0");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("O Rh +")) {
            abt.setText("0");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("100");
            rhp.setText("75");
            rhn.setText("25");
        } else if (mbt.getSelectedItem().equals("O Rh +") && fbt.getSelectedItem().equals("O Rh -")) {
            abt.setText("0");
            bbt.setText("0");
            abbt.setText("0");
            obt.setText("100");
            rhp.setText("0");
            rhn.setText("100");
        }


    }//GEN-LAST:event_btestimateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mbt.setSelectedIndex(0);
        fbt.setSelectedIndex(0);
        abt.setText("");
        bbt.setText("");
        abbt.setText("");
        obt.setText("");
        rhp.setText("");
        rhn.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abbt;
    private javax.swing.JTextField abt;
    private javax.swing.JTextField bbt;
    private javax.swing.JButton btestimate;
    private javax.swing.JComboBox<String> fbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mbt;
    private javax.swing.JTextField obt;
    private javax.swing.JTextField rhn;
    private javax.swing.JTextField rhp;
    // End of variables declaration//GEN-END:variables
}
