/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import static com.mysql.cj.MysqlType.SET;
import static com.oracle.util.Checksums.update;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import static java.awt.event.PaintEvent.UPDATE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asadujjaman(181311066)
 */
public class docupdate extends javax.swing.JFrame {

    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form docupdate
     */
    public docupdate() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        duspecialist = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        duemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        duregn = new javax.swing.JTextField();
        duname = new javax.swing.JTextField();
        dufather = new javax.swing.JTextField();
        dugender = new javax.swing.JTextField();
        duvillage = new javax.swing.JTextField();
        duphone = new javax.swing.JTextField();
        duhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dupdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dupass = new javax.swing.JPasswordField();
        dusearch = new javax.swing.JButton();
        duregn1 = new javax.swing.JTextField();
        duname1 = new javax.swing.JTextField();
        dufather1 = new javax.swing.JTextField();
        dugender1 = new javax.swing.JTextField();
        duspecialist1 = new javax.swing.JComboBox<>();
        duvillage1 = new javax.swing.JTextField();
        duphone1 = new javax.swing.JTextField();
        dupass1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ddelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        duvhour = new javax.swing.JTextField();
        duvhour1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dubranch1 = new javax.swing.JTextField();
        dubranch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1017, 734));

        duspecialist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Specialist", "Anesthesiologist", "Dentist", "Endocrinologist", "Nephrologist", "Surgeon", "ENT Specialist", "Parasitologist", "Pathologist", "Pediatrician", "Psychiatrist", "Radiologist", "Gynaecologist", "Dermatologist", " ", " ", " " }));
        duspecialist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duspecialistActionPerformed(evt);
            }
        });
        duspecialist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duspecialistKeyPressed(evt);
            }
        });

        jLabel2.setText("Email:");

        duemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duemailKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Phone:");

        duregn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duregnKeyPressed(evt);
            }
        });

        duname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dunameActionPerformed(evt);
            }
        });
        duname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dunameKeyPressed(evt);
            }
        });

        dufather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dufatherActionPerformed(evt);
            }
        });
        dufather.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dufatherKeyPressed(evt);
            }
        });

        dugender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dugenderKeyPressed(evt);
            }
        });

        duvillage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duvillageActionPerformed(evt);
            }
        });
        duvillage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duvillageKeyPressed(evt);
            }
        });

        duphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duphoneKeyPressed(evt);
            }
        });

        duhome.setText("Home");
        duhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        duhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duhomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Update Doctor's Info");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Registration Number:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Father's Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Gender:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("specialist:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Permanent Addeess");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("City/Village:");

        dupdate.setText("Update");
        dupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupdateActionPerformed(evt);
            }
        });
        dupdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dupdateKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Pass");

        dupass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dupassKeyPressed(evt);
            }
        });

        dusearch.setText("search");
        dusearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dusearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dusearchActionPerformed(evt);
            }
        });
        dusearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dusearchKeyPressed(evt);
            }
        });

        duregn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duregn1KeyPressed(evt);
            }
        });

        duname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duname1ActionPerformed(evt);
            }
        });
        duname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duname1KeyPressed(evt);
            }
        });

        dufather1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dufather1ActionPerformed(evt);
            }
        });
        dufather1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dufather1KeyPressed(evt);
            }
        });

        dugender1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dugender1KeyPressed(evt);
            }
        });

        duspecialist1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Specialist", "Anesthesiologist", "Dentist", "Endocrinologist", "Nephrologist", "Surgeon", "ENT Specialist", "Parasitologist", "Pathologist", "Pediatrician", "Psychiatrist", "Radiologist", "Gynaecologist", "Dermatologist", " ", " ", " " }));
        duspecialist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duspecialist1ActionPerformed(evt);
            }
        });
        duspecialist1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duspecialist1KeyPressed(evt);
            }
        });

        duvillage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duvillage1ActionPerformed(evt);
            }
        });
        duvillage1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duvillage1KeyPressed(evt);
            }
        });

        duphone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duphone1KeyPressed(evt);
            }
        });

        dupass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dupass1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Registered Info: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Updated Info: ");

        ddelete.setText("Delete");
        ddelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddeleteActionPerformed(evt);
            }
        });

        jLabel14.setText("Visiting Hours:");

        duvhour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duvhourKeyPressed(evt);
            }
        });

        duvhour1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duvhour1KeyPressed(evt);
            }
        });

        jLabel15.setText("Branch:");

        dubranch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dubranch1KeyPressed(evt);
            }
        });

        dubranch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dubranchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(duhome)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(595, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(duspecialist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(88, 88, 88))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dugender)
                                        .addGap(71, 71, 71))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(duemail)
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(duname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(duregn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dupass, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dufather, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dusearch))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dubranch, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(duvhour, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(duvillage, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(duphone))
                                        .addGap(71, 71, 71)))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(339, 339, 339))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dupass1)
                                .addGap(2, 2, 2))
                            .addComponent(duvhour1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(duname1)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(duvillage1)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(duspecialist1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dugender1)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dufather1)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(duregn1)
                                        .addGap(2, 2, 2))
                                    .addComponent(duphone1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(dubranch1)
                            .addComponent(dupdate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duhome)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dupass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dupass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dusearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duregn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duregn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dufather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dufather1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dugender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dugender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duspecialist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duspecialist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duvillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duvillage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duphone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(duvhour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duvhour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dubranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(dubranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddelete)
                    .addComponent(dupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duspecialistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duspecialistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duspecialistActionPerformed

    private void duspecialistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duspecialistKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duvillage.requestFocus();
        }
    }//GEN-LAST:event_duspecialistKeyPressed

    private void duemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duemailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dupass.requestFocus();
        }
    }//GEN-LAST:event_duemailKeyPressed

    private void duregnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duregnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duname.requestFocus();
        }
    }//GEN-LAST:event_duregnKeyPressed

    private void dunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dunameActionPerformed

    private void dunameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dunameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dufather.requestFocus();
        }
    }//GEN-LAST:event_dunameKeyPressed

    private void dufatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dufatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dufatherActionPerformed

    private void dufatherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dufatherKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dugender.requestFocus();
        }
    }//GEN-LAST:event_dufatherKeyPressed

    private void dugenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dugenderKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duspecialist.requestFocus();
        }
    }//GEN-LAST:event_dugenderKeyPressed

    private void duvillageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duvillageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duvillageActionPerformed

    private void duvillageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duvillageKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duphone.requestFocus();
        }
    }//GEN-LAST:event_duvillageKeyPressed

    private void duphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duphoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duvhour.requestFocus();
        }
    }//GEN-LAST:event_duphoneKeyPressed

    private void duhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duhomeActionPerformed
        // TODO add your handling code here:
        new main_admin_control().setVisible(true);

        dispose();
    }//GEN-LAST:event_duhomeActionPerformed

    private void dupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupdateActionPerformed

        try {

            Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
            String sql = "select * from doctor_db where email= '" + duemail.getText() + "'and password='" + dupass.getText() + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String email = rs.getString("email");
                String query = "update doctor_db set Password='" + dupass1.getText() + "',regno='" + duregn1.getText() + "',"
                        + "name='" + duname1.getText() + "',fathername='" + dufather1.getText() + "',gender='" + dugender1.getText() + "',"
                        + "specialist='" + (String) duspecialist1.getSelectedItem() + "',village='" + duvillage1.getText() + "',"
                        + "phone='" + duphone1.getText() + "',vhours='" + duvhour1.getText() + "',branch='" + dubranch1.getText() + "'"
                        + "where email='" + email + "'";
                pst = conn.prepareStatement(query);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Updated Successfully :)");
                duregn.setText("");
                duname.setText("");
                dupass.setText("");
                dufather.setText("");
                dugender.setText("");
                duname.setText("");
                dupass.setText("");
                duspecialist.setSelectedIndex(0);
                duvillage.setText("");
                duphone.setText("");
                duemail.setText("");

                duregn1.setText("");
                duname1.setText("");
                dupass1.setText("");
                dufather1.setText("");
                dugender1.setText("");
                duname1.setText("");
                dupass1.setText("");
                duspecialist1.setSelectedIndex(0);
                duvillage1.setText("");
                duphone1.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "Wrong Email or Password.....!!!!");
                duemail.setText("");
                dupass.setText("");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dupdateActionPerformed

    private void dusearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dusearchActionPerformed
        try {
            Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");

            String sql = "select * from doctor_db where email= '" + duemail.getText() + "'and password='" + dupass.getText() + "' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                duregn.setText(rs.getString("regno"));
                duname.setText(rs.getString("name"));

                dufather.setText(rs.getString("fathername"));
                dugender.setText(rs.getString("gender"));

                duspecialist.setSelectedItem(rs.getString("specialist"));
                duvillage.setText(rs.getString("village"));

                duphone.setText(rs.getString("phone"));
                duvhour.setText(rs.getString("vhours"));
                dubranch.setText(rs.getString("branch"));
            } else {
                JOptionPane.showMessageDialog(null, "This Email is not Registered");
                duemail.setText("");
                dupass.setText("");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dusearchActionPerformed

    private void duregn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duregn1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duname1.requestFocus();
        }
    }//GEN-LAST:event_duregn1KeyPressed

    private void duname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duname1ActionPerformed

    private void duname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duname1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dufather1.requestFocus();
        }
    }//GEN-LAST:event_duname1KeyPressed

    private void dufather1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dufather1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dufather1ActionPerformed

    private void dufather1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dufather1KeyPressed
        // TODO add your handling code here:if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dugender1.requestFocus();
        }
    }//GEN-LAST:event_dufather1KeyPressed

    private void dugender1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dugender1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duspecialist1.requestFocus();
        }
    }//GEN-LAST:event_dugender1KeyPressed

    private void duspecialist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duspecialist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duspecialist1ActionPerformed

    private void duspecialist1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duspecialist1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duvillage1.requestFocus();
        }
    }//GEN-LAST:event_duspecialist1KeyPressed

    private void duvillage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duvillage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duvillage1ActionPerformed

    private void duvillage1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duvillage1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duphone1.requestFocus();
        }
    }//GEN-LAST:event_duvillage1KeyPressed

    private void duphone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duphone1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duvhour1.requestFocus();
        }
    }//GEN-LAST:event_duphone1KeyPressed

    private void dupassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dupassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dusearch.requestFocus();
        }
    }//GEN-LAST:event_dupassKeyPressed

    private void dusearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dusearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dusearch.doClick();
            dupass1.requestFocus();
        }
    }//GEN-LAST:event_dusearchKeyPressed

    private void dupass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dupass1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duregn1.requestFocus();
        }
    }//GEN-LAST:event_dupass1KeyPressed

    private void dupdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dupdateKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dupdate.doClick();
        }
    }//GEN-LAST:event_dupdateKeyPressed

    private void ddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddeleteActionPerformed
        // TODO add your handling code here:

        try {
            Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
            String sql = "delete from doctor_db where email= '" + duemail.getText() + "' and regno = '" + duregn.getText() + "' ";
            pst = conn.prepareStatement(sql);

            pst.execute();

            JOptionPane.showMessageDialog(null, "Deleted Successfully........!");
            duregn.setText("");
            duname.setText("");
            dupass.setText("");
            dufather.setText("");
            dugender.setText("");
            duname.setText("");
            dupass.setText("");
            duspecialist.setSelectedIndex(0);
            duvillage.setText("");
            duphone.setText("");
            duemail.setText("");
            duvhour.setText("");
            dubranch.setText("");

            duregn1.setText("");
            duname1.setText("");
            dupass1.setText("");
            dufather1.setText("");
            dugender1.setText("");
            duname1.setText("");
            dupass1.setText("");
            duspecialist1.setSelectedIndex(0);
            duvillage1.setText("");
            duphone1.setText("");
            duvhour1.setText("");
            dubranch1.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "asadadad");

        } finally {
            try {
                rs.close();
                pst.close();
                //conn.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_ddeleteActionPerformed

    private void duvhour1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duvhour1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dubranch1.requestFocus();
        }
    }//GEN-LAST:event_duvhour1KeyPressed

    private void duvhourKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duvhourKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dubranch.requestFocus();
        }
    }//GEN-LAST:event_duvhourKeyPressed

    private void dubranchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dubranchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ddelete.requestFocus();
            ddelete.doClick();
        }
    }//GEN-LAST:event_dubranchKeyPressed

    private void dubranch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dubranch1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dupdate.doClick();
        }
    }//GEN-LAST:event_dubranch1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(docupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(docupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(docupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(docupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new docupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ddelete;
    private javax.swing.JTextField dubranch;
    private javax.swing.JTextField dubranch1;
    private javax.swing.JTextField duemail;
    private javax.swing.JTextField dufather;
    private javax.swing.JTextField dufather1;
    private javax.swing.JTextField dugender;
    private javax.swing.JTextField dugender1;
    private javax.swing.JButton duhome;
    private javax.swing.JTextField duname;
    private javax.swing.JTextField duname1;
    private javax.swing.JPasswordField dupass;
    private javax.swing.JPasswordField dupass1;
    private javax.swing.JButton dupdate;
    private javax.swing.JTextField duphone;
    private javax.swing.JTextField duphone1;
    private javax.swing.JTextField duregn;
    private javax.swing.JTextField duregn1;
    private javax.swing.JButton dusearch;
    private javax.swing.JComboBox<String> duspecialist;
    private javax.swing.JComboBox<String> duspecialist1;
    private javax.swing.JTextField duvhour;
    private javax.swing.JTextField duvhour1;
    private javax.swing.JTextField duvillage;
    private javax.swing.JTextField duvillage1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
